import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        "surface-1": "var(--surface-1)",
        "surface-2": "var(--surface-2)",
        border: "var(--border)",
        "border-accent": "var(--border-accent)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        "fill-primary": "var(--fill-primary)",
        "on-primary": "var(--on-primary)",
        "fill-accent": "var(--fill-accent)",
        "fill-accent-strong": "var(--fill-accent-strong)",
        "on-accent": "var(--on-accent)",
        "bg-purple": "var(--bg-purple)",
        "text-label": "var(--text-label)",
        "bg-accent": "var(--bg-accent)",
        "text-accent": "var(--text-accent)",
        "bg-success": "var(--bg-success)",
        "text-success": "var(--text-success)",
        "bg-warning": "var(--bg-warning)",
        "text-warning": "var(--text-warning)",
        "bg-tag": "var(--bg-tag)",
        "text-tag": "var(--text-tag)",
        "brand-indigo-1": "var(--brand-indigo-1)",
        "brand-indigo-2": "var(--brand-indigo-2)",
        "brand-amber-1": "var(--brand-amber-1)",
        "brand-amber-2": "var(--brand-amber-2)",
        "brand-lavender": "var(--brand-lavender)",
        "on-gradient": "var(--on-gradient)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
      },
      borderRadius: {
        "radius-sm": "var(--radius-sm)",
        radius: "var(--radius)",
        "radius-lg": "var(--radius-lg)",
        "radius-hero": "var(--radius-hero)",
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        8: "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
      },
      fontSize: {
        meta: ["var(--text-meta)", { lineHeight: "1.45" }],
        body: ["var(--text-body)", { lineHeight: "1.5" }],
        lede: ["var(--text-lede)", { lineHeight: "1.5" }],
      },
      backgroundImage: {
        "grad-horizon": "var(--grad-horizon)",
        "grad-rouse": "var(--grad-rouse)",
        "grad-noon": "var(--grad-noon)",
        "grad-ink-fade": "var(--grad-ink-fade)",
        "grad-card": "var(--grad-card)",
        "grad-dusk": "var(--grad-dusk)",
        "grad-route": "var(--grad-route)",
        "grad-portal-wash": "var(--grad-portal-wash)",
      },
      maxWidth: {
        page: "var(--page-max)",
        shell: "var(--shell-max)",
      },
    },
  },
};

export default config;
