import type { PageHomeDocument, SiteSettingsDocument } from "@/types/cms";

/**
 * Last-resort public CMS shells used only when Firestore is unreachable.
 * Mirrors operational seed content so the marketing site stays readable
 * during quota / outage windows instead of rendering a blank page.
 */
export const FALLBACK_SITE_SETTINGS: SiteSettingsDocument = {
  siteName: "Venturo",
  tagline: "Your next step, engineered.",
  siteDescription: "Your next step, engineered.",
  brandMark: "V",
  footerCopyright: "© {year} {siteName}",
  footerAttributionPrefix: "Made with ❤️ by",
  footerAttributionName: "FLYN.AI",
  footerAttributionUrl: "https://myflynai.com/",
  youtubePlaylistUrl: "",
  youtubeSyncEnabled: true,
  youtubeHomepageLimit: 3,
  youtubeLibraryLimit: 12,
  navLabels: {
    siteName: "Venturo",
    companySection: "Company",
    talentSection: "Talent",
    employersSection: "Employers",
    about: "About",
    careers: "Careers",
    journal: "Journal",
    browseRoles: "Browse roles",
    howItWorks: "How it works",
    credits: "Credits",
    pricing: "Pricing",
    tracks: "Tracks",
    requestTalent: "Request talent",
    forCompanies: "For companies",
    signIn: "Log in",
    headerCta: "Start your journey",
    headerCtaHref: "/sign-up",
    contact: "Contact",
  },
  adminNavLabels: {
    dashboard: "Dashboard",
    levers: "Program Levers",
    crm: "CRM",
    library: "Content Library",
    content: "Homepage Content",
    settings: "Settings",
    account: "My account",
    integrations: "Integrations",
    users: "Users",
  },
  studentNavLabels: {
    dashboard: "Dashboard",
    wallet: "Wallet",
    store: "Content store",
    profile: "Profile",
    settings: "Settings",
  },
  employerNavLabels: {
    dashboard: "Dashboard",
    talentPool: "Talent pool",
    pipeline: "Pipeline",
    shortlist: "Shortlist",
    profile: "Profile",
    settings: "Settings",
  },
};

export const FALLBACK_PAGE_HOME: PageHomeDocument = {
  eyebrowText: "Relocation. Engineered.",
  headline: "Your next step,",
  headlineEmphasis: "engineered.",
  subtext:
    "Venturo pairs you with a personal coach, a vetted employer, and a visa-ready path abroad — from first application to first day.",
  ctaPrimaryLabel: "Explore open roles",
  ctaPrimaryHref: "/careers-talent",
  ctaSecondaryLabel: "I'm hiring",
  ctaSecondaryHref: "/request-talent",
  hubLabel: "DXB",
  currentRoutesLabel: "Current routes",
  currentRoutesItems: [
    { code: "AMS" },
    { code: "BER" },
    { code: "CAI" },
    { code: "WAW" },
    { code: "PAR" },
    { code: "LIS" },
    { code: "DXB" },
  ],
  routesMarquee: {
    enabled: true,
    speedSec: 28,
    direction: "ltr",
    easing: "linear",
    pauseOnHover: true,
    separator: " · ",
  },
  globalReachEyebrow: "Global reach",
  globalReachHeadline: "Six corridors. One arrival city.",
  globalReachBody:
    "Every route on this map is live — a coach on one end, a vetted employer on the other, and a candidate somewhere mid-flight.",
  corridorChips: [
    { chip: "AMS → DXB" },
    { chip: "BER → DXB" },
    { chip: "CAI → DXB" },
    { chip: "WAW → DXB" },
    { chip: "PAR → DXB" },
    { chip: "LIS → DXB" },
  ],
  corridorChipsMarquee: {
    enabled: true,
    speedSec: 24,
    direction: "ltr",
    easing: "linear",
    pauseOnHover: true,
  },
  originCities: [
    {
      code: "AMS",
      label: "Amsterdam",
      initials: "AM",
      x: 80,
      y: 140,
      avatarX: 80,
      avatarY: 105,
    },
    {
      code: "BER",
      label: "Berlin",
      initials: "BE",
      x: 70,
      y: 250,
      avatarX: 55,
      avatarY: 250,
    },
    {
      code: "CAI",
      label: "Cairo",
      initials: "CA",
      x: 90,
      y: 360,
      avatarX: 78,
      avatarY: 398,
    },
    {
      code: "WAW",
      label: "Warsaw",
      initials: "WA",
      x: 420,
      y: 120,
      avatarX: 430,
      avatarY: 85,
    },
    {
      code: "PAR",
      label: "Paris",
      initials: "PA",
      x: 440,
      y: 260,
      avatarX: 465,
      avatarY: 260,
    },
    {
      code: "LIS",
      label: "Lisbon",
      initials: "LI",
      x: 410,
      y: 380,
      avatarX: 425,
      avatarY: 405,
    },
  ],
  boardingPass: {
    routeLabel: "AMS → DXB",
    passengerLabel: "Passenger",
    passengerValue: "You",
    coachLabel: "Coach",
    coachValue: "Assigned coach",
    statusLabel: "Status",
    statusValue: "Boarding",
    classLabel: "Class",
    classValue: "Track B",
    refLabel: "Ref",
    refValue: "VENTURO",
  },
  itineraryEyebrow: "The itinerary",
  itineraryHeadline: "Three legs. One arrival.",
  storiesEyebrow: "Stories",
  storiesHeadline: "Hear it from them.",
  storiesManagedLabel: "Managed in admin · Homepage content",
  podcastEyebrow: "The Move Podcast",
  podcastHeadline: "Conversations from the route.",
  podcastManagedLabel: "Managed in admin · Homepage content",
  testimonialQuote:
    "Six weeks ago I was refreshing job boards in Amsterdam. Today I'm running brand for a scale-up in Dubai — and my coach was in my corner for every leg of it.",
  testimonialAttribution: "Sara K. · Marketing lead · Placed via Venturo",
  testimonialBadge: "Placed {year}",
  talentCta: {
    eyebrow: "For talent",
    title: "Your seat is waiting.",
    body: "Free to join. Earn your first credits on welcome.",
    ctaLabel: "Get started",
    ctaHref: "/sign-up",
  },
  companyCta: {
    eyebrow: "For companies",
    title: "A pool, pre-flown.",
    body: "Every candidate is pre-screened and coached before you see them.",
    ctaLabel: "View plans",
    ctaHref: "/pricing",
  },
  rolesCta: {
    eyebrow: "Open seats",
    title: "Roles, ready now.",
    body: "Browse live openings across corridors — visa-ready paths included.",
    ctaLabel: "Browse roles",
    ctaHref: "/careers-talent",
  },
  steps: [
    {
      legNumber: 1,
      phaseLabel: "LEG 01 · Check-in",
      title: "Build your profile",
      description:
        "Tell us your skills, sector, and where you want to land. Your coach verifies and sharpens it.",
    },
    {
      legNumber: 2,
      phaseLabel: "LEG 02 · Boarding",
      title: "Get matched & coached",
      description:
        "We introduce you to vetted employers, and coach you through every interview and offer.",
    },
    {
      legNumber: 3,
      phaseLabel: "LEG 03 · Arrival",
      title: "Placed & supported",
      description:
        "From signed offer to your first ninety days, your coach stays on the route with you.",
    },
  ],
  statBlocks: [
    {
      label: "Active students",
      value: "0",
      metric: "active_students",
      suffix: "+",
    },
    {
      label: "Partner employers",
      value: "0",
      metric: "active_companies",
      suffix: "+",
    },
    {
      label: "Avg. time to place",
      value: "—",
      metric: "avg_time_to_place",
    },
    {
      label: "Placed this year",
      value: "0",
      metric: "placed_this_year",
      suffix: "+",
    },
  ],
};
